# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jtian <jtian@student.42.fr>                +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/08/31 19:26:20 by jtian             #+#    #+#              #
#    Updated: 2021/08/31 19:31:07 by jtian            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

OUTPUT = main.c
OBJECT = main.o

all:
	gcc -Wall -Wextra -Werror -o do-op $(OUTPUT) 
	
clean:
	/bin/rm -f do-op $(OBJECT) 
